/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_CULTIVAI_PB_H_INCLUDED
#define PB_CULTIVAI_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _AnimalData {
    pb_callback_t tag_id; /* ID del microchip FDX-B */
    uint32_t battery_level; /* 0-100% */
    bool scanning; /* Estado del lector */
} AnimalData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define AnimalData_init_default                  {{{NULL}, NULL}, 0, 0}
#define AnimalData_init_zero                     {{{NULL}, NULL}, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define AnimalData_tag_id_tag                    1
#define AnimalData_battery_level_tag             2
#define AnimalData_scanning_tag                  3

/* Struct field encoding specification for nanopb */
#define AnimalData_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   tag_id,            1) \
X(a, STATIC,   SINGULAR, UINT32,   battery_level,     2) \
X(a, STATIC,   SINGULAR, BOOL,     scanning,          3)
#define AnimalData_CALLBACK pb_default_field_callback
#define AnimalData_DEFAULT NULL

extern const pb_msgdesc_t AnimalData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AnimalData_fields &AnimalData_msg

/* Maximum encoded size of messages (where known) */
/* AnimalData_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
